# Generated by Django 5.0.2 on 2026-01-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_id_alter_module_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('standalone', 'Standalone'), ('subscription', 'Subscription')], max_length=20)),
                ('standalone_courses', models.ManyToManyField(blank=True, related_name='standalone_students', to='courses.course')),
            ],
        ),
    ]
