# Generated by Django 5.0.2 on 2026-01-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_id_alter_module_id_and_more'),
        ('enrollments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subscription_courses',
            field=models.ManyToManyField(blank=True, related_name='subscription_students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subscriptionplan'),
        ),
    ]
