# Generated by Django 5.0.2 on 2026-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('instructors', '0004_alter_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='selected_instructors', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
