# Generated by Django 5.0.2 on 2026-01-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash'), ('bank', 'Bank')], max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
        ),
    ]
