# Generated by Django 5.0.2 on 2026-01-27 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_id_alter_module_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('nok_first_name', models.CharField(max_length=50)),
                ('nok_last_name', models.CharField(max_length=50)),
                ('nok_email', models.EmailField(blank=True, max_length=254)),
                ('nok_phone', models.CharField(max_length=20)),
                ('nok_relationship', models.CharField(max_length=50)),
                ('nok_occupation', models.CharField(blank=True, max_length=50)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('driving_exam_date', models.DateField(blank=True, null=True)),
                ('driving_pdl_date', models.DateField(blank=True, null=True)),
                ('driving_pdl', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('courses', models.ManyToManyField(blank=True, to='courses.course')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('date_graded', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
