# Generated by Django 5.0.2 on 2026-02-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_id_alter_coursecategory_id_and_more'),
        ('instructors', '0004_alter_instructor_id'),
        ('students', '0003_alter_student_id_alter_studentmodule_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodule',
            options={'ordering': ['module__order']},
        ),
        migrations.AddField(
            model_name='studentmodule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_modules', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='studentmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='studentmodule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='students.student'),
        ),
    ]
