# Generated by Django 5.0.2 on 2026-02-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id_alter_module_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('practical', 'Practical'), ('theory', 'Theory')], max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.coursecategory'),
        ),
    ]
