# Generated by Django 6.0.1 on 2026-01-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=15, unique=True)),
                ('instructor_id', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('nok_first_name', models.CharField(max_length=50)),
                ('nok_last_name', models.CharField(max_length=50)),
                ('nok_email', models.EmailField(blank=True, max_length=254)),
                ('nok_phone', models.CharField(max_length=20)),
                ('nok_relationship', models.CharField(max_length=50)),
                ('nok_occupation', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
