# Generated by Django 5.0.2 on 2026-02-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_module_category'),
        ('instructors', '0002_alter_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_category', to='courses.coursecategory'),
        ),
    ]
