# Generated by Django 5.0.2 on 2026-02-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_alter_instructor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
    ]
