# Generated by Django 5.0.2 on 2026-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_alter_instructor_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
