# Generated by Django 5.0.2 on 2026-02-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_instructor_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='national_id',
        ),
    ]
